
DROP TABLE IF EXISTS MY_USER;
DROP SEQUENCE IF EXISTS MY_USER_SEQ;

CREATE TABLE MY_USER (
  MY_USER_ID INT PRIMARY KEY,
  USERNAME VARCHAR(250) NOT NULL,
  ENC_PASSWORD VARCHAR(250) NOT NULL,
  IS_LOCKED INT NOT NULL,
  IS_DISABLED INT NOT NULL,
  FAILED_ATTEMPTS INT NOT NULL,
  LAST_PASSWORD_DATE DATE NOT NULL,
  IS_PW_EXPIRED INT NOT NULL
);

CREATE TABLE MY_LOGIN_ATTEMPT (
    MY_LOGIN_ATTEMPT_ID INT PRIMARY KEY,
	USERNAME VARCHAR(250) NOT NULL,
	RECORD_DATE TImESTAMP NOT NULL,
	IP_ADDRESS VARCHAR(250) NULL
);

CREATE TABLE MY_PASSWORD_HIST (
    MY_PASSWORD_HIST_ID INT PRIMARY KEY,
	MY_USER_ID VARCHAR(250) NOT NULL,
	ENC_PASSWORD VARCHAR(250) NOT NULL,
	RECORD_DATE TImESTAMP NOT NULL
);

CREATE SEQUENCE MY_PASSWORD_HIST_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MY_LOGIN_ATTEMPT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MY_USER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE DUMMY (
  DUMMY_INT INT,
  DUMMY_VARCHAR VARCHAR(250),
  DUMMY_DATE DATE
);



------ Start Spring Session ----
CREATE TABLE SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES IMAGE NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

